extends Control
class_name CameraSystem

# Shows one camera's background plus an overlay for every student standing on
# a spot that camera can see, with static on top and a FNAF-style minimap of
# clickable camera buttons. It knows nothing about graphs or movement, it only
# asks GameManager "who is on spot X?".

# Fired when the player switches to a different camera.
signal camera_changed(camera_id: String)
# Fired when a student walks onto or off a spot the CURRENT camera sees.
signal watched_spot_changed(camera_id: String)

# Where the art lives. Must match build_asset_layout.gd.
#   background: res://assets/cameras/F1_CAM_HallL.png
#   overlay:    res://assets/students/bees/F1_CAM_HallL/F1_AtriumL.png (see Animatronic)
#   minimap:    res://assets/ui/map_F1.png  (optional, drawn under the buttons)
const BACKGROUND_ART := "res://assets/cameras/%s.png"
const MAP_ART := "res://assets/ui/map_%s.png"

# The tool's coordinate space for one floor. Map positions are in this space.
const MAP_SPACE := Vector2(1060, 650)
# Marked "YOU" on the minimap.
const OFFICE_SPOT := "F1_PrincipalOffice"
# View cones drawn from each camera on the minimap
const CONE_LENGTH := 60.0
const CONE_HALF_ANGLE := deg_to_rad(28.0)

# Which spots each camera sees, and where everything sits on the minimap.
# Generated by generate_graphs.gd.
@export var camera_map: CameraMap = preload("res://data/graphs/cameras.tres")
# Floor shown when the night starts (the Principal Office floor).
@export var starting_floor := "F1"
# Text listing who's on the camera, incl. missing art. Turn off once real art is in.
@export var show_debug := true

@export_group("Static")
@export var static_idle := 0.12     # constant grain while watching
@export var static_burst := 0.9     # peak of a burst
@export var static_fade_time := 0.45

@onready var bg_display: TextureRect = %CameraBackground
@onready var overlays: Control = %Overlays
@onready var static_rect: ColorRect = %Static
@onready var cam_name: Label = %CamName
@onready var debug_info: Label = %DebugInfo
@onready var cam_map: Control = %CamMap
@onready var floor_buttons: HBoxContainer = %FloorButtons

var game_manager: GameManager
var current_camera := ""
var current_floor := ""

var _bg_cache: Dictionary = {}          # path -> Texture2D or null (missing)
var _camera_group := ButtonGroup.new()  # only one camera button pressed at a time
var _floor_group := ButtonGroup.new()
var _map_tex: Texture2D = null          # optional minimap art for the current floor
var _map_rect := Rect2()                # part of the tool's floor space the minimap shows
var _static_tween: Tween

func _ready() -> void:
	# If this sits under a Node2D (not a Control), anchors can't stretch it,
	# so size it to the window here and on every resize.
	_fit_to_window()
	get_viewport().size_changed.connect(_fit_to_window)

	game_manager = get_tree().get_first_node_in_group("game_manager") as GameManager
	game_manager.student_moved.connect(_on_student_moved)
	debug_info.visible = show_debug
	_set_static(static_idle)

	# The minimap draws its own spots/lines; buttons are its children
	cam_map.draw.connect(_draw_map)
	cam_map.resized.connect(_layout_map)

	_build_floor_buttons()
	var floors := get_floors()
	if floors.is_empty():
		push_warning("CameraSystem: camera map is empty.")
		return
	# Deferred so every student has registered its spot before the first draw
	switch_floor.call_deferred(starting_floor if starting_floor in floors else floors[0])

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Switches the whole camera panel to another floor.
# Input: a floor prefix, e.g. "F0" or "F1"
# Output: none. Rebuilds the minimap buttons and shows that floor's first camera.
func switch_floor(floor_id: String) -> void:
	current_floor = floor_id
	for b: Button in floor_buttons.get_children():
		b.set_pressed_no_signal(b.get_meta("floor") == floor_id)

	_clear(cam_map)
	var cams := get_cameras_on_floor(floor_id)
	for cam in cams:
		var b := CamMapButton.new()
		b.label = cam.trim_prefix(floor_id + "_CAM_")   # "F1_CAM_HallL" -> "HallL"
		b.button_group = _camera_group
		b.set_meta("camera", cam)
		b.pressed.connect(show_camera.bind(cam))
		cam_map.add_child(b)

	var art := MAP_ART % floor_id
	_map_tex = load(art) if ResourceLoader.exists(art) else null
	_layout_map()

	if not cams.is_empty():
		show_camera(cams[0])

# Call this whenever the player picks a different camera to look at.
# Input: a camera id, e.g. "F1_CAM_HallL"
# Output: none. Redraws background + overlays, bursts static, emits camera_changed.
func show_camera(camera_id: String) -> void:
	var switched := camera_id != current_camera
	current_camera = camera_id
	for b in cam_map.get_children():
		if b is BaseButton:
			b.set_pressed_no_signal(b.get_meta("camera") == camera_id)
			b.queue_redraw()   # set_pressed_no_signal doesn't redraw by itself
	cam_name.text = "CAM  " + camera_id.trim_prefix(floor_of(camera_id) + "_CAM_")
	_refresh()
	cam_map.queue_redraw()
	if switched:
		burst_static()
		camera_changed.emit(camera_id)

# A burst of static that fades back to the idle grain.
# Input: peak strength 0..1 (defaults to static_burst)
# Output: none
func burst_static(amount: float = -1.0) -> void:
	if amount < 0.0:
		amount = static_burst
	if _static_tween:
		_static_tween.kill()
	_static_tween = create_tween()
	_static_tween.tween_method(_set_static, amount, static_idle, static_fade_time)

# Output: every floor prefix that has at least one camera, sorted. e.g. ["F0", "F1"]
func get_floors() -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		var f := floor_of(cam)
		if f not in out:
			out.append(f)
	out.sort()
	return out

# Input: "F1"  Output: ["F1_CAM_Biology", "F1_CAM_Chemistry", ...] sorted
func get_cameras_on_floor(floor_id: String) -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		if floor_of(cam) == floor_id:
			out.append(cam)
	out.sort()
	return out

# Input: any id with a floor prefix, e.g. "F1_CAM_HallL" or "F1_HallL2"
# Output: "F1"
static func floor_of(id: String) -> String:
	return id.get_slice("_", 0)

# ---------------------------------------------------------------------------
# Drawing the feed
# ---------------------------------------------------------------------------

func _refresh() -> void:
	bg_display.texture = _get_background(current_camera)
	_clear(overlays)

	var lines := PackedStringArray([current_camera])
	if bg_display.texture == null:
		lines.append("  (no background art yet)")

	var anyone := false
	# Spots are drawn in the order the camera map lists them (back to front),
	# so students on later spots end up on top.
	for spot: String in camera_map.cameras.get(current_camera, []):
		for student: Animatronic in game_manager.get_students_at(spot):
			anyone = true
			var frame := student.get_frame_for(current_camera, spot)
			if frame:
				_add_overlay(frame)
			lines.append("  %s at %s%s" % [student.get_art_name(), spot, "" if frame else "  (no art yet)"])

	if not anyone:
		lines.append("  nobody here")
	debug_info.text = "\n".join(lines)

func _add_overlay(tex: Texture2D) -> void:
	var r := TextureRect.new()
	r.texture = tex
	r.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	r.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	overlays.add_child(r)
	r.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

# Input: camera id. Output: its background, or null if the PNG doesn't exist yet.
func _get_background(camera_id: String) -> Texture2D:
	var path := BACKGROUND_ART % camera_id
	if not _bg_cache.has(path):
		_bg_cache[path] = load(path) if ResourceLoader.exists(path) else null
	return _bg_cache[path]

func _set_static(value: float) -> void:
	(static_rect.material as ShaderMaterial).set_shader_parameter("intensity", value)

# ---------------------------------------------------------------------------
# Minimap
# ---------------------------------------------------------------------------

# Picks which part of the floor the minimap shows: the whole floor when there's
# map art (so the art lines up), otherwise just the area around this floor's
# cameras and spots, so the map uses its space well.
func _compute_map_rect() -> Rect2:
	if _map_tex:
		return Rect2(Vector2.ZERO, MAP_SPACE)
	var r := Rect2()
	var first := true
	for id: String in camera_map.positions:
		if floor_of(id) != current_floor:
			continue
		var p: Vector2 = camera_map.positions[id]
		if first:
			r = Rect2(p, Vector2.ZERO)
			first = false
		else:
			r = r.expand(p)
	if first:
		return Rect2(Vector2.ZERO, MAP_SPACE)
	return r.grow(50.0)

# Input: a point in the tool's floor space. Output: the same point on the minimap.
func _to_map(p: Vector2) -> Vector2:
	var s: float = min(cam_map.size.x / _map_rect.size.x, cam_map.size.y / _map_rect.size.y)
	var offset := (cam_map.size - _map_rect.size * s) / 2.0
	return offset + (p - _map_rect.position) * s

# Places every camera button where its camera sits on the floor.
func _layout_map() -> void:
	if current_floor == "":
		return
	_map_rect = _compute_map_rect()
	var fallback_x := 8.0
	for b in cam_map.get_children():
		if not b is BaseButton:
			continue
		var cam: String = b.get_meta("camera")
		if camera_map.positions.has(cam):
			b.position = _to_map(camera_map.positions[cam]) - b.size / 2.0
		else:
			# No position exported yet: line it up along the bottom
			b.position = Vector2(fallback_x, cam_map.size.y - b.size.y - 8.0)
			fallback_x += b.size.x + 6.0
	cam_map.queue_redraw()

# Draws the minimap panel, the spots, and a "YOU" marker. Buttons draw on top.
func _draw_map() -> void:
	var font := ThemeDB.fallback_font
	# cam_map.draw_rect(Rect2(Vector2.ZERO, cam_map.size), Color(0, 0, 0, 0.6))

	if _map_tex:
		var s: float = min(cam_map.size.x / _map_rect.size.x, cam_map.size.y / _map_rect.size.y)
		cam_map.draw_texture_rect(_map_tex, Rect2(_to_map(Vector2.ZERO), MAP_SPACE * s), false)
	else:
		var seen: Array = camera_map.cameras.get(current_camera, [])
		for id: String in camera_map.positions:
			if floor_of(id) != current_floor or "_CAM_" in id:
				continue
			var p := _to_map(camera_map.positions[id])
			if id in seen:
				cam_map.draw_circle(p, 5.0, Color(1, 1, 1, 0.9))
			else:
				cam_map.draw_circle(p, 3.0, Color(1, 1, 1, 0.3))
	
	_draw_cones()
	
	if camera_map.positions.has(OFFICE_SPOT) and floor_of(OFFICE_SPOT) == current_floor:
		var o := _to_map(camera_map.positions[OFFICE_SPOT])
		cam_map.draw_rect(Rect2(o - Vector2(9, 9), Vector2(18, 18)), Color(1, 1, 1, 0.9), false, 2.0)
		cam_map.draw_string(font, o + Vector2(-14, 26), "YOU", HORIZONTAL_ALIGNMENT_LEFT, -1, 18, Color.WHITE)

	# cam_map.draw_rect(Rect2(Vector2.ZERO, cam_map.size), Color(1, 1, 1, 0.5), false, 2.0)
	cam_map.draw_string(font, Vector2(10, cam_map.size.y - 10), "Floor " + current_floor.trim_prefix("F"), HORIZONTAL_ALIGNMENT_LEFT, -1, 18, Color(1, 1, 1, 0.7))

# Draws a view cone from every camera on this floor, pointing at the middle of
# the spots it sees. Drawn under the buttons; the watched camera's cone is amber.
func _draw_cones() -> void:
	for cam in get_cameras_on_floor(current_floor):
		if not camera_map.positions.has(cam):
			continue
		var origin := _to_map(camera_map.positions[cam])

		# Aim at the average position of the spots this camera sees
		var target := Vector2.ZERO
		var count := 0
		for spot: String in camera_map.cameras.get(cam, []):
			if camera_map.positions.has(spot) and floor_of(spot) == current_floor:
				target += _to_map(camera_map.positions[spot])
				count += 1
		if count == 0:
			continue
		var angle := (target / count - origin).angle()

		# A fan-shaped wedge: the tip at the camera, an arc at the far end
		var pts := PackedVector2Array([origin])
		var steps := 10
		for i in steps + 1:
			var a := angle - CONE_HALF_ANGLE + (2.0 * CONE_HALF_ANGLE) * i / steps
			pts.append(origin + Vector2.from_angle(a) * CONE_LENGTH)
		var watched := cam == current_camera
		var fill := Color(1.0, 0.8, 0.35, 0.35) if watched else Color(1, 1, 1, 0.12)
		cam_map.draw_colored_polygon(pts, fill)

func _build_floor_buttons() -> void:
	for f in get_floors():
		var b := Button.new()
		b.text = "Floor " + f.trim_prefix("F")   # "F1" -> "Floor 1"
		b.toggle_mode = true
		b.button_group = _floor_group
		b.focus_mode = Control.FOCUS_NONE
		b.set_meta("floor", f)
		b.pressed.connect(switch_floor.bind(f))
		floor_buttons.add_child(b)

# Removes all children right away (queue_free alone keeps them around, and
# counted, until the end of the frame).
func _clear(parent: Node) -> void:
	for c in parent.get_children():
		parent.remove_child(c)
		c.queue_free()

func _fit_to_window() -> void:
	if get_parent() is Control:
		return   # a Control parent (like the tablet) already sizes us
	position = Vector2.ZERO
	size = get_viewport_rect().size

# Redraw only if the move touched a spot the current camera can see,
# with a short static flicker, the classic "something moved" tell.
func _on_student_moved(_student: Animatronic, from_spot: String, to_spot: String) -> void:
	var seen: Array = camera_map.cameras.get(current_camera, [])
	if from_spot in seen or to_spot in seen:
		_refresh()
		burst_static(static_burst * 0.6)
		watched_spot_changed.emit(current_camera)
