extends Control
class_name CameraSystem

# Pure display: shows one camera's background plus an overlay for every
# student standing on a spot that camera can see. It knows nothing about
# graphs or movement, it only asks GameManager "who is on spot X?".

# Where the art lives. Must match build_asset_layout.gd.
#   background: res://assets/cameras/F1_CAM_HallL.png
#   overlay:    res://assets/students/bees/F1_CAM_HallL/F1_AtriumL.png (see Animatronic)
const BACKGROUND_ART := "res://assets/cameras/%s.png"

# Which spots each camera sees. Generated by generate_graphs.gd.
@export var camera_map: CameraMap = preload("res://data/graphs/cameras.tres")
# Floor shown when the night starts (the Principal Office floor).
@export var starting_floor := "F1"
# Top-left text listing the camera and who's on it, incl. missing art.
# Turn off once real art is in.
@export var show_debug := true

@onready var bg_display: TextureRect = %CameraBackground
@onready var overlays: Control = %Overlays
@onready var debug_info: Label = %DebugInfo
@onready var camera_buttons: HBoxContainer = %CameraButtons
@onready var floor_buttons: HBoxContainer = %FloorButtons

var game_manager: GameManager
var current_camera := ""
var current_floor := ""

var _bg_cache: Dictionary = {}       # path -> Texture2D or null (missing)
var _camera_group := ButtonGroup.new()  # only one camera button pressed at a time
var _floor_group := ButtonGroup.new()

func _ready() -> void:
	# night.tscn's root is a Node2D, and anchors only stretch a Control to fill
	# its parent when that parent is also a Control. So size it to the window
	# here, and again whenever the window is resized.
	_fit_to_window()
	get_viewport().size_changed.connect(_fit_to_window)

	game_manager = get_tree().get_first_node_in_group("game_manager") as GameManager
	game_manager.student_moved.connect(_on_student_moved)
	debug_info.visible = show_debug

	_build_floor_buttons()
	var floors := get_floors()
	if floors.is_empty():
		push_warning("CameraSystem: camera map is empty.")
		return
	switch_floor(starting_floor if starting_floor in floors else floors[0])

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Switches the whole camera panel to another floor.
# Input: a floor prefix, e.g. "F0" or "F1"
# Output: none. Rebuilds the camera buttons and shows that floor's first camera.
func switch_floor(floor_id: String) -> void:
	current_floor = floor_id
	for b: Button in floor_buttons.get_children():
		b.set_pressed_no_signal(b.get_meta("floor") == floor_id)

	_clear(camera_buttons)
	var cams := get_cameras_on_floor(floor_id)
	for cam in cams:
		var b := Button.new()
		b.text = cam.trim_prefix(floor_id + "_CAM_")   # "F1_CAM_HallL" -> "HallL"
		b.toggle_mode = true
		b.button_group = _camera_group
		b.set_meta("camera", cam)
		b.pressed.connect(show_camera.bind(cam))
		camera_buttons.add_child(b)

	if not cams.is_empty():
		show_camera(cams[0])

# Call this whenever the player picks a different camera to look at.
# Input: a camera id, e.g. "F1_CAM_HallL"
# Output: none — redraws background + overlays.
func show_camera(camera_id: String) -> void:
	current_camera = camera_id
	for b: Button in camera_buttons.get_children():
		b.set_pressed_no_signal(b.get_meta("camera") == camera_id)
	_refresh()

# Output: every floor prefix that has at least one camera, sorted.
#   e.g. ["F0", "F1"]
func get_floors() -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		var f := floor_of(cam)
		if f not in out:
			out.append(f)
	out.sort()
	return out

# Input: "F1"  Output: ["F1_CAM_Biology", "F1_CAM_Chemistry", ...] sorted
func get_cameras_on_floor(floor_id: String) -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		if floor_of(cam) == floor_id:
			out.append(cam)
	out.sort()
	return out

# Input: any id with a floor prefix, e.g. "F1_CAM_HallL" or "F1_HallL2"
# Output: "F1"
static func floor_of(id: String) -> String:
	return id.get_slice("_", 0)

# ---------------------------------------------------------------------------
# Drawing
# ---------------------------------------------------------------------------

func _refresh() -> void:
	bg_display.texture = _get_background(current_camera)

	_clear(overlays)

	var lines := PackedStringArray(["CAM  " + current_camera])
	if bg_display.texture == null:
		lines.append("  (no background art yet)")

	var anyone := false
	# Spots are drawn in the order the camera map lists them, so list them
	# back to front (farthest spot first) and closer students draw on top.
	for spot: String in camera_map.cameras.get(current_camera, []):
		for student: Animatronic in game_manager.get_students_at(spot):
			anyone = true
			var frame := student.get_frame_for(current_camera, spot)
			if frame:
				_add_overlay(frame)
			lines.append("  %s at %s%s" % [student.get_art_name(), spot, "" if frame else "  (no art yet)"])

	if not anyone:
		lines.append("  nobody here")
	debug_info.text = "\n".join(lines)

func _add_overlay(tex: Texture2D) -> void:
	var r := TextureRect.new()
	r.texture = tex
	r.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	r.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	overlays.add_child(r)
	r.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

# Input: camera id. Output: its background, or null if the PNG doesn't exist yet.
func _get_background(camera_id: String) -> Texture2D:
	var path := BACKGROUND_ART % camera_id
	if not _bg_cache.has(path):
		_bg_cache[path] = load(path) if ResourceLoader.exists(path) else null
	return _bg_cache[path]

func _build_floor_buttons() -> void:
	for f in get_floors():
		var b := Button.new()
		b.text = "Floor " + f.trim_prefix("F")   # "F1" -> "Floor 1"
		b.toggle_mode = true
		b.button_group = _floor_group
		b.set_meta("floor", f)
		b.pressed.connect(switch_floor.bind(f))
		floor_buttons.add_child(b)

# Removes all children right away (queue_free alone keeps them around, and
# counted, until the end of the frame).
func _clear(parent: Node) -> void:
	for c in parent.get_children():
		parent.remove_child(c)
		c.queue_free()

func _fit_to_window() -> void:
	position = Vector2.ZERO
	size = get_viewport_rect().size

# Redraw only if the move touched a spot the current camera can see.
func _on_student_moved(_student: Animatronic, from_spot: String, to_spot: String) -> void:
	var seen: Array = camera_map.cameras.get(current_camera, [])
	if from_spot in seen or to_spot in seen:
		_refresh()
