extends Control
class_name CameraSystem

# Shows one camera's background plus an overlay for every student standing on
# a spot that camera can see, with static on top and a FNAF-style minimap of
# clickable camera buttons. It knows nothing about graphs or movement, it only
# asks GameManager "who is on spot X?".

# Fired when the player switches to a different camera.
signal camera_changed(camera_id: String)
# Fired when a student walks onto or off a spot the CURRENT camera sees.
signal watched_spot_changed(camera_id: String)

# Where the art lives. Must match build_asset_layout.gd.
#   background: res://assets/cameras/F1_CAM_HallL.png
#   overlay:    res://assets/students/bees/F1_CAM_HallL/F1_AtriumL.png (see Animatronic)
#   minimap:    res://assets/ui/map_F1.png  (optional, drawn under the buttons)
const BACKGROUND_ART := "res://assets/cameras/%s.png"
const MAP_ART := "res://assets/ui/map_%s.png"
# Font for all tablet text (Anton, SIL Open Font License, see assets/fonts/OFL.txt).
# Every label and button under this node inherits it through the theme.
const UI_FONT: Font = preload("res://assets/fonts/Anton-Regular.ttf")

# The tool's coordinate space for one floor. Map positions are in this space.
const MAP_SPACE := Vector2(1060, 650)
# Marked "YOU" on the minimap.
const OFFICE_SPOT := "F1_PrincipalOffice"
# View cones drawn from each camera on the minimap
const CONE_LENGTH := 60.0
const CONE_HALF_ANGLE := deg_to_rad(28.0)
# Floor tab colours, the same as the camera circles in cam_map_button.gd
const FLOOR_IDLE := Color(0.12, 0.13, 0.15)
const FLOOR_RING := Color(1, 1, 1, 0.85)
const FLOOR_ACTIVE := Color(1.0, 0.8, 0.35)

# Which spots each camera sees, and where everything sits on the minimap.
# Generated by generate_graphs.gd.
@export var camera_map: CameraMap = preload("res://data/graphs/cameras.tres")
# Floor shown when the night starts (the Principal Office floor).
@export var starting_floor := "F1"
# Text listing who's on the camera, incl. missing art. Turn off once real art is in.
@export var show_debug := true

@export_group("Static")
@export var static_idle := 0.12     # constant grain while watching
@export var static_burst := 0.9     # peak of a burst
@export var static_fade_time := 0.45

@onready var bg_display: TextureRect = %CameraBackground
@onready var overlays: Control = %Overlays
@onready var static_rect: ColorRect = %Static
@onready var cam_name: Label = %CamName
@onready var debug_info: Label = %DebugInfo
@onready var cam_map: Control = %CamMap
@onready var floor_buttons: HBoxContainer = %FloorButtons

var game_manager: GameManager
var current_camera := ""   # the camera on the feed
var current_floor := ""    # the floor the MINIMAP shows (can differ from the feed's floor)
# False while nobody can see the feed (tablet down). While false, student
# moves don't redraw, burst static or emit watched_spot_changed.
# Set it with set_active().
var active := true

var _bg_cache: Dictionary = {}          # path -> Texture2D or null (missing)
var _camera_group := ButtonGroup.new()  # only one camera button pressed at a time
var _floor_group := ButtonGroup.new()
var _map_tex: Texture2D = null          # optional minimap art for the current floor
var _map_rect := Rect2()                # part of the tool's floor space the minimap shows
var _static_tween: Tween

# --- Teacher dispatch (sending a teacher to a room, e.g. to stop Joe) ---
var teacher: TeacherDispatch = null     # found in the scene; null = no teacher button
var dispatch_mode := false              # true while the room points are showing
var _teacher_btn: Button
var _teacher_status: Label
var _status_timer: SceneTreeTimer

func _ready() -> void:
	# One theme on this node sets the font for every Control below it,
	# including the camera circles and floor tabs created in code.
	theme = Theme.new()
	theme.default_font = UI_FONT

	# If this sits under a Node2D (not a Control), anchors can't stretch it,
	# so size it to the window here and on every resize.
	_fit_to_window()
	get_viewport().size_changed.connect(_fit_to_window)

	game_manager = get_tree().get_first_node_in_group("game_manager") as GameManager
	game_manager.student_moved.connect(_on_student_moved)
	debug_info.visible = show_debug
	_set_static(static_idle)

	# The minimap draws its own spots/lines; buttons are its children
	cam_map.draw.connect(_draw_map)
	cam_map.resized.connect(_layout_map)

	_build_floor_buttons()
	var floors := get_floors()
	if floors.is_empty():
		push_warning("CameraSystem: camera map is empty.")
		return
	# Deferred so every student has registered its spot before the first draw
	_start.call_deferred(starting_floor if starting_floor in floors else floors[0])

# Shows the starting floor on the minimap and its first camera on the feed.
func _start(floor_id: String) -> void:
	_setup_teacher()
	switch_floor(floor_id)
	var cams := get_cameras_on_floor(floor_id)
	if not cams.is_empty():
		show_camera(cams[0])

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Called by the tablet when it goes up or down.
# Input: true while the player can see the feed, false while they can't
# Output: none. Turning it on redraws the feed, so anything that moved while
#         the tablet was down is already in place when it comes up.
func set_active(on: bool) -> void:
	if on == active:
		return
	active = on
	if active and current_camera != "":
		_refresh()

# Switches the MINIMAP to another floor. The feed keeps showing whatever
# camera it was on, so you can browse another floor's map without losing it.
# Input: a floor prefix, e.g. "F0" or "F1"
# Output: none. Rebuilds the minimap buttons. No camera on the new floor is
#         selected, unless the feed's camera happens to be on it.
func switch_floor(floor_id: String) -> void:
	current_floor = floor_id
	for b: Button in floor_buttons.get_children():
		b.set_pressed_no_signal(b.get_meta("floor") == floor_id)

	_clear(cam_map)
	for cam in get_cameras_on_floor(floor_id):
		var b := CamMapButton.new()
		b.label = cam.trim_prefix(floor_id + "_CAM_")   # "F1_CAM_HallL" -> "HallL"
		b.button_group = _camera_group
		b.set_meta("camera", cam)
		b.pressed.connect(show_camera.bind(cam))
		cam_map.add_child(b)
		b.set_pressed_no_signal(cam == current_camera)

	var art := MAP_ART % floor_id
	_map_tex = load(art) if ResourceLoader.exists(art) else null
	_rebuild_points()

# Call this whenever the player picks a different camera to look at.
# Input: a camera id, e.g. "F1_CAM_HallL"
# Output: none. Redraws background + overlays, bursts static, emits camera_changed.
func show_camera(camera_id: String) -> void:
	var switched := camera_id != current_camera
	current_camera = camera_id
	for b in cam_map.get_children():
		if b is BaseButton and b.has_meta("camera"):
			b.set_pressed_no_signal(b.get_meta("camera") == camera_id)
			b.queue_redraw()   # set_pressed_no_signal doesn't redraw by itself
	cam_name.text = "CAM  " + camera_id.trim_prefix(floor_of(camera_id) + "_CAM_")
	_refresh()
	cam_map.queue_redraw()
	if switched:
		burst_static()
		camera_changed.emit(camera_id)

# A burst of static that fades back to the idle grain.
# Input: peak strength 0..1 (defaults to static_burst)
# Output: none
func burst_static(amount: float = -1.0) -> void:
	if amount < 0.0:
		amount = static_burst
	if _static_tween:
		_static_tween.kill()
	_static_tween = create_tween()
	_static_tween.tween_method(_set_static, amount, static_idle, static_fade_time)

# Output: every floor prefix that has at least one camera, sorted. e.g. ["F0", "F1"]
func get_floors() -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		var f := floor_of(cam)
		if f not in out:
			out.append(f)
	out.sort()
	return out

# Input: "F1"  Output: ["F1_CAM_Biology", "F1_CAM_Chemistry", ...] sorted
func get_cameras_on_floor(floor_id: String) -> Array[String]:
	var out: Array[String] = []
	for cam: String in camera_map.cameras:
		if floor_of(cam) == floor_id:
			out.append(cam)
	out.sort()
	return out

# Input: any id with a floor prefix, e.g. "F1_CAM_HallL" or "F1_HallL2"
# Output: "F1"
static func floor_of(id: String) -> String:
	return id.get_slice("_", 0)

# ---------------------------------------------------------------------------
# Drawing the feed
# ---------------------------------------------------------------------------

func _refresh() -> void:
	bg_display.texture = _get_background(current_camera)
	_clear(overlays)

	var lines := PackedStringArray([current_camera])
	if bg_display.texture == null:
		lines.append("  (no background art yet)")

	var anyone := false
	# Spots are drawn in the order the camera map lists them (back to front),
	# so students on later spots end up on top.
	for spot: String in camera_map.cameras.get(current_camera, []):
		for student: Animatronic in game_manager.get_students_at(spot):
			anyone = true
			var frame := student.get_frame_for(current_camera, spot)
			if frame:
				_add_overlay(frame)
			lines.append("  %s at %s%s" % [student.get_art_name(), spot, "" if frame else "  (no art yet)"])

	if not anyone:
		lines.append("  nobody here")
	debug_info.text = "\n".join(lines)

func _add_overlay(tex: Texture2D) -> void:
	var r := TextureRect.new()
	r.texture = tex
	r.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
	r.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
	r.mouse_filter = Control.MOUSE_FILTER_IGNORE
	overlays.add_child(r)
	r.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)

# Input: camera id. Output: its background, or null if the PNG doesn't exist yet.
func _get_background(camera_id: String) -> Texture2D:
	var path := BACKGROUND_ART % camera_id
	if not _bg_cache.has(path):
		_bg_cache[path] = load(path) if ResourceLoader.exists(path) else null
	return _bg_cache[path]

func _set_static(value: float) -> void:
	(static_rect.material as ShaderMaterial).set_shader_parameter("intensity", value)

# ---------------------------------------------------------------------------
# Minimap
# ---------------------------------------------------------------------------

# Picks which part of the floor the minimap shows: the whole floor when there's
# map art (so the art lines up), otherwise just the area around this floor's
# cameras and spots, so the map uses its space well.
func _compute_map_rect() -> Rect2:
	if _map_tex:
		return Rect2(Vector2.ZERO, MAP_SPACE)
	var r := Rect2()
	var first := true
	for id: String in camera_map.positions:
		if floor_of(id) != current_floor:
			continue
		var p: Vector2 = camera_map.positions[id]
		if first:
			r = Rect2(p, Vector2.ZERO)
			first = false
		else:
			r = r.expand(p)
	if first:
		return Rect2(Vector2.ZERO, MAP_SPACE)
	return r.grow(50.0)

# Input: a point in the tool's floor space. Output: the same point on the minimap.
func _to_map(p: Vector2) -> Vector2:
	var s: float = min(cam_map.size.x / _map_rect.size.x, cam_map.size.y / _map_rect.size.y)
	var offset := (cam_map.size - _map_rect.size * s) / 2.0
	return offset + (p - _map_rect.position) * s

# Places every camera button where its camera sits on the floor.
func _layout_map() -> void:
	if current_floor == "":
		return
	_map_rect = _compute_map_rect()
	var fallback_x := 8.0
	for b in cam_map.get_children():
		if not b is BaseButton:
			continue
		# Camera circles carry "camera", teacher room points carry "spot"
		var id: String = b.get_meta("camera") if b.has_meta("camera") else b.get_meta("spot", "")
		if camera_map.positions.has(id):
			b.position = _to_map(camera_map.positions[id]) - b.size / 2.0
		else:
			# No position exported yet: line it up along the bottom
			b.position = Vector2(fallback_x, cam_map.size.y - b.size.y - 8.0)
			fallback_x += b.size.x + 6.0
	_place_teacher_ui()
	cam_map.queue_redraw()

# Draws the minimap panel, the spots, and a "YOU" marker. Buttons draw on top.
func _draw_map() -> void:
	var font := UI_FONT
	# cam_map.draw_rect(Rect2(Vector2.ZERO, cam_map.size), Color(0, 0, 0, 0.6))

	if _map_tex:
		var s: float = min(cam_map.size.x / _map_rect.size.x, cam_map.size.y / _map_rect.size.y)
		cam_map.draw_texture_rect(_map_tex, Rect2(_to_map(Vector2.ZERO), MAP_SPACE * s), false)
	else:
		var seen: Array = camera_map.cameras.get(current_camera, [])
		for id: String in camera_map.positions:
			if floor_of(id) != current_floor or "_CAM_" in id:
				continue
			var p := _to_map(camera_map.positions[id])
			if id in seen:
				cam_map.draw_circle(p, 5.0, Color(1, 1, 1, 0.9))
			else:
				cam_map.draw_circle(p, 3.0, Color(1, 1, 1, 0.3))
	
	_draw_cones()
	
	if camera_map.positions.has(OFFICE_SPOT) and floor_of(OFFICE_SPOT) == current_floor:
		var o := _to_map(camera_map.positions[OFFICE_SPOT])
		cam_map.draw_rect(Rect2(o - Vector2(9, 9), Vector2(18, 18)), Color(1, 1, 1, 0.9), false, 2.0)
		cam_map.draw_string(font, o + Vector2(-14, 26), "YOU", HORIZONTAL_ALIGNMENT_LEFT, -1, 18, Color.WHITE)

	# cam_map.draw_rect(Rect2(Vector2.ZERO, cam_map.size), Color(1, 1, 1, 0.5), false, 2.0)

# Draws a view cone from every camera on this floor, pointing at the middle of
# the spots it sees. Drawn under the buttons; the watched camera's cone is amber.
func _draw_cones() -> void:
	for cam in get_cameras_on_floor(current_floor):
		if not camera_map.positions.has(cam):
			continue
		var origin := _to_map(camera_map.positions[cam])

		# Aim at the average position of the spots this camera sees
		var target := Vector2.ZERO
		var count := 0
		for spot: String in camera_map.cameras.get(cam, []):
			if camera_map.positions.has(spot) and floor_of(spot) == current_floor:
				target += _to_map(camera_map.positions[spot])
				count += 1
		if count == 0:
			continue
		var angle := (target / count - origin).angle()

		# A fan-shaped wedge: the tip at the camera, an arc at the far end
		var pts := PackedVector2Array([origin])
		var steps := 10
		for i in steps + 1:
			var a := angle - CONE_HALF_ANGLE + (2.0 * CONE_HALF_ANGLE) * i / steps
			pts.append(origin + Vector2.from_angle(a) * CONE_LENGTH)
		var watched := cam == current_camera
		var fill := Color(1.0, 0.8, 0.35, 0.35) if watched else Color(1, 1, 1, 0.12)
		cam_map.draw_colored_polygon(pts, fill)
		
# ---------------------------------------------------------------------------
# Teacher dispatch UI
# ---------------------------------------------------------------------------

# Creates the TEACHER toggle (bottom-right corner of the map) and its status
# line, if the night has a TeacherDispatch node.
func _setup_teacher() -> void:
	teacher = get_tree().get_first_node_in_group("teacher_dispatch") as TeacherDispatch
	if teacher == null:
		return
	teacher.uses_changed.connect(func(_u: int) -> void: _update_teacher_button())
	teacher.teacher_arrived.connect(_on_teacher_arrived)

	_teacher_btn = Button.new()
	_teacher_btn.toggle_mode = true
	_teacher_btn.focus_mode = Control.FOCUS_NONE
	_teacher_btn.mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND
	_teacher_btn.custom_minimum_size = Vector2(190, 42)
	_teacher_btn.add_theme_font_size_override("font_size", 18)
	var idle := _floor_style(FLOOR_IDLE, FLOOR_RING, 2)
	var on := _floor_style(MapPointButton.COLOR, MapPointButton.COLOR, 2)
	_teacher_btn.add_theme_stylebox_override("normal", idle)
	_teacher_btn.add_theme_stylebox_override("hover", _floor_style(FLOOR_IDLE, Color.WHITE, 3))
	_teacher_btn.add_theme_stylebox_override("pressed", on)
	_teacher_btn.add_theme_stylebox_override("hover_pressed", on)
	_teacher_btn.add_theme_stylebox_override("disabled", _floor_style(FLOOR_IDLE, Color(1, 1, 1, 0.25), 2))
	_teacher_btn.add_theme_color_override("font_color", Color.WHITE)
	_teacher_btn.add_theme_color_override("font_pressed_color", FLOOR_IDLE)
	_teacher_btn.add_theme_color_override("font_hover_pressed_color", FLOOR_IDLE)
	_teacher_btn.add_theme_color_override("font_disabled_color", Color(1, 1, 1, 0.4))
	_teacher_btn.toggled.connect(_set_dispatch_mode)
	add_child(_teacher_btn)   # added after CamMap, so it draws on top of the map

	_teacher_status = Label.new()
	_teacher_status.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT
	_teacher_status.add_theme_font_size_override("font_size", 18)
	_teacher_status.add_theme_constant_override("outline_size", 6)
	_teacher_status.add_theme_color_override("font_outline_color", Color.BLACK)
	_teacher_status.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(_teacher_status)

	_update_teacher_button()

# Keeps the button in the map's bottom-right corner, the status line above it
func _place_teacher_ui() -> void:
	if _teacher_btn == null:
		return
	_teacher_btn.size = _teacher_btn.custom_minimum_size
	_teacher_btn.position = cam_map.position + cam_map.size - _teacher_btn.size - Vector2(8, 8)
	_teacher_status.size = Vector2(cam_map.size.x - 16, 28)
	_teacher_status.position = Vector2(cam_map.position.x + 8, _teacher_btn.position.y - 34)

# Button text shows how many teachers are left, or why you can't send one
func _update_teacher_button() -> void:
	if _teacher_btn == null:
		return
	if teacher.en_route_spot != "":
		_teacher_btn.text = "TEACHER ON THE WAY"
	elif teacher.uses == 0:
		_teacher_btn.text = "NO TEACHERS LEFT"
	else:
		_teacher_btn.text = "TEACHER  %d/%d" % [teacher.uses, teacher.max_uses]
	_teacher_btn.disabled = not teacher.can_send()
	if _teacher_btn.disabled and dispatch_mode:
		_teacher_btn.button_pressed = false   # turns dispatch mode off too

# Input: true to show the room points, false to hide them
func _set_dispatch_mode(on: bool) -> void:
	dispatch_mode = on
	_rebuild_points()
	if on:
		_show_status("Pick a room to send a teacher to")

# Recreates the green room points for the current floor (only in dispatch mode)
func _rebuild_points() -> void:
	for c in cam_map.get_children():
		if c.has_meta("spot"):
			cam_map.remove_child(c)
			c.queue_free()
	if dispatch_mode:
		for id: String in camera_map.positions:
			if floor_of(id) != current_floor or "_CAM_" in id or id == OFFICE_SPOT:
				continue
			var p := MapPointButton.new()
			p.label = id.trim_prefix(current_floor + "_")   # "F1_1B" -> "1B"
			p.set_meta("spot", id)
			p.pressed.connect(_on_point_pressed.bind(id))
			cam_map.add_child(p)
	_layout_map()

func _on_point_pressed(spot: String) -> void:
	if teacher.send_teacher(spot):
		_teacher_btn.button_pressed = false   # hides the points
		_show_status("Teacher on the way to " + spot.trim_prefix(floor_of(spot) + "_") + "...", 999.0)
	_update_teacher_button()

func _on_teacher_arrived(spot: String, stopped_joe: bool) -> void:
	var room := spot.trim_prefix(floor_of(spot) + "_")
	_show_status("Teacher stopped Joe in " + room + "!" if stopped_joe else "Nobody in " + room + ".")
	_update_teacher_button()

# Shows a line above the TEACHER button, cleared after a few seconds
func _show_status(text: String, seconds := 4.0) -> void:
	if _teacher_status == null:
		return
	_teacher_status.text = text
	var t := get_tree().create_timer(seconds)
	_status_timer = t
	t.timeout.connect(func() -> void:
		if _status_timer == t:   # a newer message replaced this one: leave it
			_teacher_status.text = "")

# Floor tabs above the minimap, styled like the camera circles: dark with a
# white outline, amber when it's the floor the minimap is showing.
func _build_floor_buttons() -> void:
	floor_buttons.add_theme_constant_override("separation", 8)

	var idle := _floor_style(FLOOR_IDLE, FLOOR_RING, 2)
	var hover := _floor_style(FLOOR_IDLE, Color.WHITE, 3)
	var on := _floor_style(FLOOR_ACTIVE, FLOOR_ACTIVE, 2)

	for f in get_floors():
		var b := Button.new()
		b.text = "FLOOR " + f.trim_prefix("F")   # "F1" -> "FLOOR 1"
		b.toggle_mode = true
		b.button_group = _floor_group
		b.focus_mode = Control.FOCUS_NONE
		b.mouse_default_cursor_shape = Control.CURSOR_POINTING_HAND
		b.custom_minimum_size = Vector2(120, 42)

		b.add_theme_font_size_override("font_size", 18)
		b.add_theme_stylebox_override("normal", idle)
		b.add_theme_stylebox_override("hover", hover)
		b.add_theme_stylebox_override("pressed", on)
		b.add_theme_stylebox_override("hover_pressed", on)
		# Light text on the dark tabs, dark text on the amber one
		b.add_theme_color_override("font_color", Color.WHITE)
		b.add_theme_color_override("font_hover_color", Color.WHITE)
		b.add_theme_color_override("font_pressed_color", FLOOR_IDLE)
		b.add_theme_color_override("font_hover_pressed_color", FLOOR_IDLE)

		b.set_meta("floor", f)
		b.pressed.connect(switch_floor.bind(f))
		floor_buttons.add_child(b)

# Input: fill colour, outline colour, outline thickness in pixels
# Output: a rounded box used as one state of a floor tab
func _floor_style(fill: Color, border: Color, border_width: int) -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = fill
	s.border_color = border
	s.set_border_width_all(border_width)
	s.set_corner_radius_all(6)
	s.content_margin_left = 18.0
	s.content_margin_right = 18.0
	s.content_margin_top = 6.0
	s.content_margin_bottom = 6.0
	return s

# Removes all children right away (queue_free alone keeps them around, and
# counted, until the end of the frame).
func _clear(parent: Node) -> void:
	for c in parent.get_children():
		parent.remove_child(c)
		c.queue_free()

func _fit_to_window() -> void:
	if get_parent() is Control:
		return   # a Control parent (like the tablet) already sizes us
	position = Vector2.ZERO
	size = get_viewport_rect().size

# Redraw only if the move touched a spot the current camera can see,
# with a short static flicker, the classic "something moved" tell.
func _on_student_moved(_student: Animatronic, from_spot: String, to_spot: String) -> void:
	if not active:
		return   # tablet is down: set_active(true) catches up when it opens
	var seen: Array = camera_map.cameras.get(current_camera, [])
	if from_spot in seen or to_spot in seen:
		_refresh()
		burst_static(static_burst * 0.6)
		watched_spot_changed.emit(current_camera)
