@tool
extends EditorScript

# Builds the asset folder layout from the camera map + every student graph,
# then reports which images are missing (and which ones nothing uses anymore).
#
# How to run: open this file in the Script editor, then File > Run
# (Ctrl+Shift+X). Results print to the Output tab and are also written to
# res://assets/asset_checklist.md.
#
# Re-run it whenever you change cameras, graphs or spot names. It never
# deletes anything, it only creates missing folders and reports.

const GRAPHS_DIR := "res://data/graphs"
const CAMERAS_FILE := "res://data/graphs/cameras.tres"
const ASSETS := "res://assets"
const REPORT := "res://assets/asset_checklist.md"

func _run() -> void:
	var cameras := load(CAMERAS_FILE) as CameraMap
	if cameras == null:
		push_error("Couldn't load %s. Run the graph generator first." % CAMERAS_FILE)
		return

	var students := _load_student_graphs()   # "bees" -> StudentGraph
	if students.is_empty():
		push_warning("No graph_*.tres files found in %s." % GRAPHS_DIR)

	# Every image the game will look for: { "path": ..., "label": ... }
	var expected: Array = []

	# --- 1. One background per camera ---
	_make_dir(ASSETS.path_join("cameras"))
	for cam in cameras.cameras:
		expected.append({
			"path": ASSETS.path_join("cameras").path_join(cam + ".png"),
			"label": "Background: %s" % cam,
		})

	# --- 2. One overlay per student x camera x spot that camera sees ---
	# Only spots that are actually in that student's graph count, so a
	# camera Bees never walks past gets no Bees folder at all.
	for student in students:
		var g: StudentGraph = students[student]
		for cam in cameras.cameras:
			var seen: Array = []
			for spot in cameras.cameras[cam]:
				if g.nodes.has(spot):
					seen.append(spot)
			if seen.is_empty():
				continue
			var dir := ASSETS.path_join("students").path_join(student).path_join(cam)
			_make_dir(dir)
			for spot in seen:
				expected.append({
					"path": dir.path_join(spot + ".png"),
					"label": "%s on %s, seen from %s" % [student, spot, cam],
				})

	# --- 3. Compare with what's on disk ---
	var expected_paths := {}
	var missing: Array = []
	for e in expected:
		expected_paths[e["path"]] = true
		if not FileAccess.file_exists(e["path"]):
			missing.append(e)

	# Images that exist but nothing looks for (e.g. after renaming a spot)
	var on_disk: Array = []
	_list_pngs(ASSETS.path_join("cameras"), on_disk)
	_list_pngs(ASSETS.path_join("students"), on_disk)
	var unused: Array = on_disk.filter(func(p): return not expected_paths.has(p))

	_print_report(expected, missing, unused)
	_write_report(expected, missing, unused)

	# Refresh the FileSystem dock so the new folders show up right away
	EditorInterface.get_resource_filesystem().scan()

# Input: none (reads every graph_<name>.tres in GRAPHS_DIR)
# Output: { "bees": StudentGraph, "meer": StudentGraph, ... }
func _load_student_graphs() -> Dictionary:
	var out := {}
	var d := DirAccess.open(GRAPHS_DIR)
	if d == null:
		return out
	for f in d.get_files():
		if f.begins_with("graph_") and f.ends_with(".tres"):
			var g := load(GRAPHS_DIR.path_join(f)) as StudentGraph
			if g:
				out[f.trim_prefix("graph_").trim_suffix(".tres")] = g
	return out

func _make_dir(path: String) -> void:
	if not DirAccess.dir_exists_absolute(path):
		DirAccess.make_dir_recursive_absolute(path)

# Collects every .png under a folder, recursively, into "out".
func _list_pngs(dir: String, out: Array) -> void:
	var d := DirAccess.open(dir)
	if d == null:
		return
	for f in d.get_files():
		if f.ends_with(".png"):
			out.append(dir.path_join(f))
	for sub in d.get_directories():
		if not sub.begins_with("."):
			_list_pngs(dir.path_join(sub), out)

func _print_report(expected: Array, missing: Array, unused: Array) -> void:
	print("=== Asset layout ===")
	print("%d images needed, %d done, %d missing" % [expected.size(), expected.size() - missing.size(), missing.size()])
	for e in missing:
		print("  MISSING  %s   (%s)" % [e["path"], e["label"]])
	for p in unused:
		print("  UNUSED   %s   (nothing looks for this anymore)" % p)
	print("Checklist written to %s" % REPORT)

func _write_report(expected: Array, missing: Array, unused: Array) -> void:
	var missing_paths := {}
	for e in missing:
		missing_paths[e["path"]] = true

	var lines: Array = []
	lines.append("# Asset checklist")
	lines.append("")
	lines.append("Generated by `build_asset_layout.gd`. Don't edit by hand, just re-run it.")
	lines.append("")
	lines.append("**%d / %d done**" % [expected.size() - missing.size(), expected.size()])
	lines.append("")
	for e in expected:
		var mark := " " if missing_paths.has(e["path"]) else "x"
		lines.append("- [%s] %s  \n  `%s`" % [mark, e["label"], e["path"]])
	if not unused.is_empty():
		lines.append("")
		lines.append("## Unused (nothing looks for these)")
		for p in unused:
			lines.append("- `%s`" % p)

	var f := FileAccess.open(REPORT, FileAccess.WRITE)
	if f:
		f.store_string("\n".join(lines) + "\n")
